version: '3.4'
services:
  web:
    image: webpage
    build: "./"
    restart: always
    working_dir: "/app"
    volumes:
      - ./index.html:/app/index.html
     
    command: bash -c "rm -rf models/* && rasa run -m models --enable-api --cors \"*\""
    ports:
      - '5005:5005'
    public: true
    networks:
      - all
      
networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
      
      rasa run -m models --enable-api --cors "*"
